### ISSUE TITLE
deserializes empty string to nil

### ISSUE THREAD

**Issue by mdemare** [dtao/safe_yaml#4]
``` yaml

---
a:
- b:
    c: ''
```

returns: `{"a"=>[{"b"=>{"c"=>nil}}]}`
expected: `{"a"=>[{"b"=>{"c"=>""}}]}`
